# Blog config
keywords: Cavalon Blog
author: Cavalon
description: Programing & Life

# icon
favicon: /images/favicon.png
avatar: /images/logo.png
logo_dir: /images/logo.png
logo_style: width:200px;

copyright:
  show: true
  default: "本文著作權為Cavalon所有，轉載請註明出處。"
  show_author: true

footbar:
  copyright: Cavalon Huang

# Social Links
# If you want to add more, go to sidebar.pug
github: https://github.com/cavalown
mail: cavalown@gmail.com
zhihu:
QQ: 
twitter:
instagram: https://www.instagram.com/cavalown/
rss:
facebook:
weibo:
linkedin: https://www.instagram.com/cavalown/

# Nav menu
menu:
  Articles: /
  Tags: /tags
  About: /about
  Timeline: /archives
  # Links: /links

# Navbar rightbtn
rightbtn:
  back: true
  search: true       # 从Icarus抠出来的搜索框，关掉可以稍微提高速度
  avatar: true


# Some settings
useSummary: true    # enable it will use summary of your posts in index
useTagCloud: false   # use tagcloud instead of tag list
tocMaxDepth: 6       # if you set 0, toc will close. The maximum is 6.


  
# Comment
disqus: cavalonHexoBlog
duoshuo: 
gentie: 
# Valine comments https://valine.js.org
valine:
  enable: false # if you want use valine, please set enable: true
  appid:  # your leancloud appid
  appkey:  # your leancloud appkey
  notify: false # true/false:mail notify !!!Test,Caution. https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
  verify: false # true/false:verify code
  avatar: retro # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  placeholder: 說說話 # comment box placeholder

